spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.43.39.136:3306/zeng?serverTimezone=UTC
    username: zyt
    password: zyt
  session:
    timeout: 86400

#线上的环境  只用改掉和公共环境不同的配置 即可